(part "HY2213-BB3A"
    (packageRef "SOT95P280X140-6N")
    (interface
        (port "1" (symbPinId 1) (portName "NC_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VDD") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VSS") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NC_2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC_3") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Hycon")
    (property "Manufacturer_Part_Number" "HY2213-BB3A")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Arrow_Part_Number" "")
    (property "Arrow_Price/Stock" "")
    (property "Description" "PMIC - Battery Management SOT-23-6 RoHS")
    (property "Datasheet_Link" "https://datasheet.lcsc.com/szlcsc/HYCON-Tech-HY2213-BB3A_C113632.pdf")
    (property "symbolName1" "HY2213-BB3A")
)
